// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: WT32_SC01_Sample2

#include "ui.h"
#include "Arduino.h"

extern void setScreenBrightness(uint16_t percent);

void slider_change_value(lv_event_t *e)
{
	int value = lv_slider_get_value(ui_DemoScreenBrightnessSlider);
	setScreenBrightness(value);
}
