// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: WT32_SC01_Sample2

#include "../ui.h"

void ui_DemoScreen_screen_init(void)
{
    ui_DemoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DemoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DemoScreen, lv_color_hex(0x223471), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DemoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DemoScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DemoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DemoScreenTitleLabel = lv_label_create(ui_DemoScreen);
    lv_obj_set_width(ui_DemoScreenTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DemoScreenTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DemoScreenTitleLabel, 0);
    lv_obj_set_y(ui_DemoScreenTitleLabel, -130);
    lv_obj_set_align(ui_DemoScreenTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DemoScreenTitleLabel, "Demo Screen");
    lv_obj_set_style_text_font(ui_DemoScreenTitleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DemoScreenBrightnessSlider = lv_slider_create(ui_DemoScreen);
    lv_slider_set_range(ui_DemoScreenBrightnessSlider, 10, 100);
    lv_slider_set_value(ui_DemoScreenBrightnessSlider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DemoScreenBrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_DemoScreenBrightnessSlider, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_DemoScreenBrightnessSlider, 7);
    lv_obj_set_width(ui_DemoScreenBrightnessSlider, lv_pct(80));
    lv_obj_set_x(ui_DemoScreenBrightnessSlider, -1);
    lv_obj_set_y(ui_DemoScreenBrightnessSlider, -59);
    lv_obj_set_align(ui_DemoScreenBrightnessSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_DemoScreenBrightnessSlider, lv_color_hex(0x87E1FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DemoScreenBrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DemoScreenBrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DemoScreenBrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DemoScreenBrightnessLabel = lv_label_create(ui_DemoScreen);
    lv_obj_set_width(ui_DemoScreenBrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DemoScreenBrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DemoScreenBrightnessLabel, -154);
    lv_obj_set_y(ui_DemoScreenBrightnessLabel, -82);
    lv_obj_set_align(ui_DemoScreenBrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DemoScreenBrightnessLabel, "Brightness");

    lv_obj_add_event_cb(ui_DemoScreenBrightnessSlider, ui_event_DemoScreenBrightnessSlider, LV_EVENT_ALL, NULL);

}
